# Generated by Django 2.2.4 on 2019-08-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
