# Generated by Django 2.2.4 on 2019-08-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPage', '0003_auto_20190812_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
